version: '3'

services:
  web1:
    build: .
    container_name: flask_web1
    restart: always
    ports:
      - "5001:5000"
    networks:
      - web_network

  web2:
    build: .
    container_name: flask_web2
    restart: always
    ports:
      - "5002:5000"
    networks:
      - web_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
     - "5000:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web_network

networks:
  web_network:
    driver: bridge